---
title: "Read data from web"
author: "Jiacheng Wu"
date: "10/30/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## NSDUH data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = 
  read_html(url) 

drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)

```


## Star wars

Get some star wars data

```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

sw_html = read_html(sw_url)

sw_titles =
  sw_html %>% 
    html_elements(".lister-item-header a") %>%
    html_text()

sw_revenue = 
  sw_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()
  
sw_df = 
  tibble(
    title = sw_titles,
    rev = sw_revenue)
```

## Napolean dynamite

```{r}
dynamite_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html =
  read_html(dynamite_url)

dynamite_review_titles = 
  dynamite_html %>% 
  html_elements(".a-text-bold span") %>% 
  html_text()
```

......

## APIs

Get some data from an API about water

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content()
```

## Json. Some datasets are harder to structure, so one might need JSON for these. 

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>% 
  as_tibble()
```

BRFSS data via API

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

Pokemon ...

```{r}
poke_data = 
  GET("https://pokeapi.co/api/v2/pokemon/1") %>% 
  content()
poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```


